CREATE TABLE usuario(
id_user INT NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
email VARCHAR(120) UNIQUE,

PRIMARY KEY(id_user)
);

CREATE TABLE notas (
id_nota INT NOT NULL AUTO_INCREMENT,
id_user INT NOT NULL,
title VARCHAR(50) NOT NULL,
body TEXT NOT NULL,
dt_nota DATE NOT NULL,

PRIMARY KEY(id_nota),
FOREIGN KEY(id_user)
    REFERENCES usuario(id_user)
);
